# Generated by Django 5.2 on 2025-04-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
