# Generated by Django 4.2.5 on 2024-03-26 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
