# Generated by Django 4.2.5 on 2024-03-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0004_feedbacks_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
