# Generated by Django 4.2.5 on 2024-03-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0005_alter_feedbacks_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctioneer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.seller'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(default='Online', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.seller')),
            ],
        ),
    ]
