# Generated by Django 4.2.5 on 2024-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0006_remove_auction_winner_auction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
