# Generated by Django 4.2.5 on 2024-03-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0011_spice_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spice',
            name='price',
        ),
        migrations.AlterField(
            model_name='spice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.seller'),
        ),
    ]
