# Generated by Django 4.2.5 on 2024-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0012_remove_spice_price_alter_spice_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Expired', 'Expired')], default='Available', max_length=50),
        ),
    ]
