# Generated by Django 5.2 on 2025-04-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0015_alter_bid_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online_wallet', 'Online Wallet'), ('other', 'Other')], default='credit_card', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='processing', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminapi.bid')),
            ],
        ),
    ]
