# Generated by Django 5.2 on 2025-04-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0016_bidpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpurchase',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.bid'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
