# Generated by Django 5.2 on 2025-05-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0017_alter_bidpurchase_bid_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
