# Generated by Django 5.2 on 2025-06-04 14:51

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0018_alter_seller_id_proof_alter_seller_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('vehicle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_copy', models.FileField(blank=True, null=True, upload_to='images')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('adminapi.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('DeliveryAgent', 'Delivery Agent')], default='Admin', max_length=50),
        ),
    ]
