# Generated by Django 5.2 on 2025-06-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0019_deliveryagent_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpurchase',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapi.deliveryagent'),
        ),
    ]
