# Generated by Django 5.2 on 2025-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0020_bidpurchase_delivery_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
